apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.ports.webui }}
    targetPort: {{ .Values.ports.webui }}
  type: LoadBalancer
---
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" .Release.Name }}
  namespace: {{ .Release.Namespace | or .Values.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.host | default (printf "my.%s.com" .Release.Name) | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ printf "%s-svc" .Release.Name }}
            port:
              number: {{ .Values.ports.webui }}
{{- end }}
